apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: ecomern-frontend
      name: ecommerce-app
  replicas: 1
  template:
    metadata:
      labels:
        app: ecomern-frontend
        name: ecommerce-app
    spec:
      containers:
        - name: ecomern-frontend
          image: thehufaaz/ecomern-frontend
          env:
            - name: REACT_APP_BASE_URL
              value: "http://18.212.122.76:30008"
      
    