apiVersion: v1
kind: Service
metadata:
  name: my-app-service-frontend
spec:
  selector:
    app: ecomern-frontend
    name: ecommerce-app
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 30005
  type: NodePort
